=== LuizSodre/JAL/SisCoServ/Aquisição/inclusao_pagamento.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:include schemaLocation="tipos_basicos.xsd" />

<!-- definition of simple elements -->
			
	<xsd:simpleType name="tsValorPago">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="15"/>
			<xsd:fractionDigits value="2" fixed="true"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="tsValorPagoRecMantidoExt">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="15"/>
			<xsd:fractionDigits value="2" fixed="true"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="tsVinculacaoNumRE">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="\d{2}/\d{10}"></xsd:pattern>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="tsVinculacaoNumDI">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="\d{2}/\d{7}-\d{1}"></xsd:pattern>
		</xsd:restriction>
	</xsd:simpleType>
	
<!-- definition of complex elements -->
	<xsd:complexType name="tcItemPagamento">
        <xsd:sequence>
            <xsd:element name="NumOpAdqEmpresa" type="tsNumOpAdqEmpresa" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="ValorPago" type="tsValorPago" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="ValorPagoRecMantidoExt" type="tsValorPagoRecMantidoExt" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

	<xsd:element name="InclusaoPagamento">
		<xsd:complexType>
        	<xsd:sequence>
            	<xsd:element name="NumeroRASEmpresa" type="tsNumeroRASEmpresa" minOccurs="1" maxOccurs="1"/>
            	<xsd:element name="IdPagamentoEmpresa" type="tsIdPagamentoEmpresa" minOccurs="1" maxOccurs="1"/>
            	<xsd:element name="NumeroPagamento" type="tsNumeroPagamento" minOccurs="1" maxOccurs="1"/>
            	<xsd:element name="DataPagamento" type="xsd:date" minOccurs="1" maxOccurs="1"/>
            	<xsd:element name="ItemPagamento" type="tcItemPagamento" minOccurs="0" maxOccurs="unbounded"/>
            	<xsd:element name="VinculacaoNumRE" type="tsVinculacaoNumRE" minOccurs="0" maxOccurs="unbounded"/>
            	<xsd:element name="VinculacaoNumDI" type="tsVinculacaoNumDI" minOccurs="0" maxOccurs="unbounded"/> 
        	</xsd:sequence>
    	</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== LuizSodre/JAL/SisCoServ/Aquisição/inclusao_pagamento.xml
<?xml version="1.0" encoding="UTF-8"?>
<InclusaoPagamento xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="inclusao_pagamento.xsd">
  <NumeroRASEmpresa></NumeroRASEmpresa>
  <IdPagamentoEmpresa></IdPagamentoEmpresa>
  <NumeroPagamento></NumeroPagamento>
  <DataPagamento></DataPagamento>
  <ItemPagamento>
    <NumOpAdqEmpresa></NumOpAdqEmpresa>
    <ValorPago></ValorPago>
    <ValorPagoRecMantidoExt></ValorPagoRecMantidoExt>
  </ItemPagamento>
  <VinculacaoNumRE></VinculacaoNumRE>
  <VinculacaoNumDI></VinculacaoNumDI>
</InclusaoPagamento>
